name: build

on: 
  pull_request:
  push:
    branches: 
      - version-test

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: install pre-reqs and build
      run: sudo ./installUbuntu.sh
    - name: test
      run: |
        ./build/usher --help
        ./build/matUtils --help
        command -v mafft
        ver=$(git ls-remote --tags https://github.com/yatisht/usher | tail -1| cut -f2)
        basename $ver >version.txt
      working-directory: ./
    - uses: EndBug/add-and-commit@v7
      with:
          default_author: github_actions
  
  ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: install pre-reqs and build
      run: sudo ./installUbuntu.sh
    - name: test
      run: |
        ./build/usher --help
        ./build/matUtils --help
        command -v mafft

  macOS-latest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: install pre-reqs and build
      run: ./installMacOS.sh
    - name: test
      run: |
        ./build/usher --help
        ./build/matUtils --help
        command -v mafft
